apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.37.2
          env:
            - name: TZ
              value: Europe/Paris
            - name: DOMAIN
              value: https://vault.noynto.me
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: INVITATIONS_ALLOWED
              value: "true"
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: IP_HEADER
              value: X-Real-IP
            - name: SHOW_PASSWORD_HINT
              value: "false"
            - name: PASSWORD_ITERATIONS
              value: "600000"
            - name: ORG_EVENTS_ENABLED
              value: "true"
            - name: EMERGENCY_ACCESS_ALLOWED
              value: "true"
            - name: SENDS_ALLOWED
              value: "true"
            - name: TRASH_AUTO_DELETE_DAYS
              value: "30"
            - name: INCOMPLETE_2FA_TIME_LIMIT
              value: "3"
            - name: LOG_LEVEL
              value: warn
            - name: EXTENDED_LOGGING
              value: "true"
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-admin-token
                  key: token
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
