apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=30.0.0 <31.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Activer le dashboard
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.local.lan`)
        entryPoints:
          - websecure

    # Ports d'entrée
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443

    # Logs
    logs:
      general:
        level: INFO
      access:
        enabled: true

    # Providers Kubernetes
    providers:
      kubernetesIngress:
        enabled: true
      kubernetesCRD:
        enabled: true
