apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eosa-admin-tls
  namespace: eosa
spec:
  secretName: eosa-admin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: admin.eosa.me
  dnsNames:
    - admin.eosa.me
