apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eosa-app
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes
  prune: true
  targetNamespace: eosa
  sourceRef:
    kind: GitRepository
    name: eosa
  dependsOn:
    - name: infrastructure-controllers
    - name: infrastructure-configs
  wait: true
  timeout: 5m
  patches:
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: eosa
        spec:
          template:
            spec:
              containers:
                - name: eosa
                  image: ghcr.io/noynto/eosa:1.6.1
      target:
        kind: Deployment
        name: eosa
    - patch: |
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: mongodb
        spec:
          template:
            spec:
              securityContext:
                fsGroup: 999
      target:
        kind: StatefulSet
        name: mongodb