apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eosa-admin
  namespace: eosa
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: eosa-admin-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "eosa administration"
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-connections: "10"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.eosa.me
      secretName: eosa-admin-tls
  rules:
    - host: admin.eosa.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eosa-admin
                port:
                  number: 18080
