apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tempo-helmrelease.yaml
  - loki-helmrelease.yaml
  - mimir-helmrelease.yaml
  - grafana-helmrelease.yaml
  - grafana-certificate.yaml
  - grafana-ingress.yaml
  - otel-collector-helmrelease.yaml